[project]
name = "one-piece-network-analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "networkx>=3.4.2",
    "numpy>=2.2.3",
    "plotly>=6.0.0",
    "polars>=1.25.1",
    "scipy>=1.15.2",
]
